# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do # lane
    sync_code_signing(type: "appstore") # action
    build_app(scheme: "MyApp") # action
    upload_to_testflight # action
    slack(message: "Successfully distributed a new beta build") # action
  end

  lane :custom_gradle_task do
    gradle(task: "hello")
  end
end
